### PR TITLE
Add backticks around types

### PR DESCRIPTION
**Pull request by krlmlr**
in error messages, for consistency.

### CODE REVIEW

**Comment by lionel-** [comment]
I don't think this is correct?

**Comment by krlmlr** [comment]
``The subscript has the wrong type `environment`. It must be `logical`, `numeric`, or `character`.``

The new backticks are consistent with the backticks after "wrong type". Should we use `<>` instead?

**Comment by lionel-** [comment]
In the first sentence this is about types, in the second this is about concepts. For instance a `<factor>` and a `<character>` are character types.

**Comment by krlmlr** [comment]
Agree to omit the backticks around the concepts.

We already have this:

```
> vec_assert(lgl(), chr()):

Error: `lgl()` must be a vector with type <character>.
Instead, it has type <logical>.
```

This makes me think we should throw `The subscript has the wrong type <environment>.` Happy to do this in a new PR.

**Pull request closed without merging**
