### PR TITLE
Rename to avoid confusion in RStudio IDE

### PR DESCRIPTION
**Pull request by krlmlr**
Ideally, the IDE would know...

### CODE REVIEW

**Comment by lionel-** [comment]
What confusion is this fixing?

**Comment by lionel-** [comment]
I'm a bit reticent to introduce ad hoc style changes that can't be implemented consistently and intuitively by code authors.

**Comment by krlmlr** [comment]
RStudio IDE thinks `new` is a keyword and messes up the syntax highlighting and highlights errors. It's not, and it shouldn't.

**Comment by lionel-** [comment]
Then I'd like proper names instead of an underscore suffix, but I don't think we should bother about this.

**Comment by krlmlr** [comment]
It's the only instance of `new` here.

**Pull request merged**
