### PR TITLE
Prevent `$<-` assignment with `NULL` from shortening list-ofs

### LINKED ISSUE #1704: For `<list_of>`, `$<-` needs to handle `NULL` like `[[<-`
i.e., don't drop the element

``` r
library(vctrs)

x <- list_of(x = 1, y = 2, z = 3)

x$y <- NULL
x
#> <list_of<double>[2]>
#> $x
#> [1] 1
#> 
#> $z
#> [1] 3

x[["z"]] <- NULL
x
#> <list_of<double>[2]>
#> $x
#> [1] 1
#> 
#> $z
#> NULL
```

<sup>Created on 2022-09-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### PR DESCRIPTION
**Pull request by DavisVaughan**
Closes #1704

### CODE REVIEW

**Review by lionel- — COMMENTED** [review]
Do we need support for `zap()`?

Should this be implemented at the `vctrs_vctr` level?

**Comment by DavisVaughan** [comment]
> Do we need support for zap()?

Do we ever want `$<-` or `[[<-` to be able to shorten lists? Being size stable feels like nice properties of these functions.

I'd prefer implementing something like `loc <- subscript_invert("a", i = 5, names = c("a", "b"))`, `vec_slice(x, loc)` to remove elements.

Or maybe:

```r
chr_as_location(i, names, ..., invert = FALSE/TRUE, oob = c("error", "remove", "extend"))

loc <- chr_as_location("a", names = c("a", "b"), invert = TRUE)
vec_slice(x, loc)
```

**Comment by DavisVaughan** [comment]
> Should this be implemented at the vctrs_vctr level?

I guess that depends on whether or not we'd want to enforce this "avoid shortening lists" behavior on all vctrs_vctr list subclasses, but it does feel kind of reasonable to do that? We'd do it for both `$<-` and `[[<-` I think.

**Comment by lionel-** [comment]
In R, lists (and to a lesser extent vectors in general) are also the type for dictionary-like objects. That's why `$<-` (and name-based `[[<-` for consistency) should be able to remove objects from lists.

Then the question becomes what happens with location-based `[[<-`. Do we allow removing elements for consistency or do we treat it differently? For tibbles it behaves the same way.

I think it's fine to keep preventing atomic vectors from being shortened though.

**Comment by DavisVaughan** [comment]
Do you mind if we merge this as-is and continue conversation in an issue for vctrs 1.0.0? I feel like at the very least we won't want `NULL` to be the way we zap elements, so this should be ok for now to at least align `$<-` and `[[<-`. I can open it and move all relevant conversation there.

**Comment by lionel-** [comment]
I'm not sure about all this. I like the idea of deleting elements with `zap()`, but I worry that it's going to be confusing to have list and list-of behave differently. I think I'd rather follow base R behaviour here, with `NULL` for deletion.

**Comment by lionel-** [comment]
By the way, if we remove this sort of syntax for name deletion, we'll need something easier than `x[-match(name, names(x))]`. The problem is that while we can do `x[-10]`, we can't do `x[-"name"]`. So removing `$<-` deletion entirely without an alternative doesn't appeal to me.

**Comment by DavisVaughan** [comment]
@lionel- that's why I mentioned `chr_as_location("a", names = c("a", "b"), invert = TRUE)` as a way to generate a location vector that would delete `"a"`.

I would never do `x[-10]` programmatically either, because of the issue with `x[-integer()]` (I kind of which `num_as_location()` had a way to force negative inversion for that case)

**Comment by DavisVaughan** [comment]
I don't think it would be unreasonable to provide `vec_remove()` as an easy way to remove elements (named or positional)

**Comment by lionel-** [comment]
> that's why I mentioned chr_as_location("a", names = c("a", "b"), invert = TRUE) as a way to generate a location vector that would delete "a".

This is not a practical alternative to `x$a <- NULL` or `zap()` though. We need something syntactic.

> I would never do x[-10] programmatically either,

My comments are mostly about analytic usages. By the way, since we return list-ofs in tidyr, I think we should keep list and list-of behaviour in line. To me that suggests we shouldn't stray too far away from base R in our `$` and `[[` methods. Also, since we make it very easy to lose the class, I think it'd be a bit unsafe to programmatically rely on special behaviour such as `NULL` preservation in `$<-`.

**Comment by DavisVaughan** [comment]
I guess I can live with `[[<-` and `$<-` inheriting base R rules (including `NULL` deletion and expansion like `x <- list(); x$y <- 1`)

And then `vec_assign2()` would be stricter, i.e. it wouldn't do `NULL` deletion with lists, and it would use `vec_as_location2()` so you can't expand the vector either. That would make `vec_assign2()` completely size stable.

So maybe I'll close this issue an open another one that actually remove the special `NULL` behavior from our `[[<-` method?

**Comment by lionel-** [comment]
That sounds good. I guess I'm slowly coming to terms with the idea that vec-assign/assign2 behaves differently than user-facing methods. Maybe at some point it'd make sense to export helpers to take care of these things and of subset-assign coercions.

**Comment by DavisVaughan** [comment]
> I guess I'm slowly coming to terms with the idea that vec-assign/assign2 behaves differently than user-facing methods.

Same, even though I didn't want that to be the case 😢

**Comment by DavisVaughan** [comment]
See https://github.com/r-lib/vctrs/issues/1704#issuecomment-1295304348

**Pull request closed without merging**
