### PR TITLE
fix type around line 183

### PR DESCRIPTION
**Pull request by njtierney**
I wanted to fix a typo around [line 183](https://github.com/r-lib/vctrs/compare/master...njtierney:master#diff-04c6e90faac2675aa89e2176d2eec7d8R183), but then in doing so it appears I don't get the same error messages, and I also change the timezone printing method on the README - which you might not want.

On another note, it's great to see this package come together, I've been keeping an eye on it for a while and it's nice to see how these ideas have been communicated! Thanks!

### CODE REVIEW

**Comment by hadley** [comment]
Do you have the latest version? It looks like you have a version where I forgot to export some methods.

If so, can you please tell me what version of R you have?

**Comment by hadley** [comment]
Ooops, no, you need the dev version of rlang.

**Comment by njtierney** [comment]
OK great! Added dev version of rlang, and here is my session info, if that is helpful.

``` r
""
#> [1] ""
```

Created on 2018-08-09 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> Session info -------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.5.1 (2018-07-02)
#>  system   x86_64, darwin15.6.0        
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_AU.UTF-8                 
#>  tz       Australia/Melbourne         
#>  date     2018-08-09
#> Packages -----------------------------------------------------------------
#>  package   * version date       source                         
#>  backports   1.1.2   2017-12-13 CRAN (R 3.5.0)                 
#>  base      * 3.5.1   2018-07-05 local                          
#>  compiler    3.5.1   2018-07-05 local                          
#>  datasets  * 3.5.1   2018-07-05 local                          
#>  devtools    1.13.6  2018-06-27 CRAN (R 3.5.0)                 
#>  digest      0.6.15  2018-01-28 CRAN (R 3.5.0)                 
#>  evaluate    0.10.1  2017-06-24 CRAN (R 3.5.0)                 
#>  graphics  * 3.5.1   2018-07-05 local                          
#>  grDevices * 3.5.1   2018-07-05 local                          
#>  htmltools   0.3.6   2017-04-28 CRAN (R 3.5.0)                 
#>  knitr       1.20    2018-02-20 CRAN (R 3.5.0)                 
#>  magrittr    1.5     2014-11-22 CRAN (R 3.5.0)                 
#>  memoise     1.1.0   2018-06-28 Github (hadley/memoise@06d16ec)
#>  methods   * 3.5.1   2018-07-05 local                          
#>  Rcpp        0.12.18 2018-07-23 cran (@0.12.18)                
#>  rmarkdown   1.10    2018-06-11 CRAN (R 3.5.0)                 
#>  rprojroot   1.3-2   2018-01-03 CRAN (R 3.5.0)                 
#>  stats     * 3.5.1   2018-07-05 local                          
#>  stringi     1.2.4   2018-07-20 cran (@1.2.4)                  
#>  stringr     1.3.1   2018-05-10 CRAN (R 3.5.0)                 
#>  tools       3.5.1   2018-07-05 local                          
#>  utils     * 3.5.1   2018-07-05 local                          
#>  withr       2.1.2   2018-03-15 CRAN (R 3.5.0)                 
#>  yaml        2.1.19  2018-05-01 CRAN (R 3.5.0)
```

</details>

**Comment by njtierney** [comment]
Also completely happy if you just want to fix the typos yourself if this PR isn't arriving at a convenient time :)

**Comment by hadley** [comment]
Thanks - I'd done quite a lot rewriting so was just easiest to do by hand.

**Comment by hadley** [comment]
Your diff does nicely illustrate base R's variation from system-to-system 😄

**Comment by njtierney** [comment]
Yes, that makes sense!

And yeah, that is interesting! Seeing time differences like that is wacky.

Also, I ran `spelling::spell_check_files("README.Rmd")` to identify the fixes - it looked like `devtools::spell_check()` doesn't check the README.

**Pull request closed without merging**
