### PR TITLE
vctrs -> pizza

### PR DESCRIPTION
**Pull request by krlmlr**
for consistency, to simplify copy-pasting. Extends #880.

### CODE REVIEW

**Comment by hadley** [comment]
I'm pretty sure we don't want to do this, since the bit at the bottom is likely to end up in another vignette.

**Comment by krlmlr** [comment]
My use case is the adaptation of an existing class to vctrs. Currently copy-pasting and search-replacing from this text seems to be the fastest option; requires consistency, hence this PR. Would you consider reviewing as a stop-gap, until we have https://github.com/r-lib/vctrs/issues/170?

**Comment by lionel-** [comment]
I was wondering if we should always use the `"my_"` namespace in examples.

**Comment by hadley** [comment]
Maybe we could call the example package "my"?

**Comment by lionel-** [comment]
Would you like to revisit this PR using the `my_` namespace @krlmlr?

**Comment by krlmlr** [comment]
Will do.

**Comment by krlmlr** [comment]
There's now :pizza: everywhere, rebased on master.

Now it's trivial to change this to "my" or to anything else. I think we should choose a longer word that will be unique in search+replace operations. There are [quite a few words ending with "my"](https://www.wordgamehelper.com/words-ending-with/my), including "dummy", not to mention [words that contain "my"](https://www.wordgamehelper.com/words-containing/my).

How about mypkg?

**Comment by lionel-** [comment]
I don’t know, I like `my`. This is the conventional namespace in Emacs lisp for personal functions and variables and I have never had a search+replace issue with it. I’m not sure what kind of problems we could expect?

**Comment by krlmlr** [comment]
It's probably fine, we only have one stray instance of "my" in the vignettes (and a few "MY" that need to be reviewed too). On the other hand, `mypkg` is 100% bulletproof now and in the future. Your call.

**Comment by krlmlr** [comment]
Should I do `pizza` -> `mypkg` or `pizza` -> `<something else>` ?

**Comment by lionel-** [comment]
The vctrs prefix is probably fine.

**Pull request closed without merging**
