### PR TITLE
Rename `fun` to `fn` in `vec_math()`

### PR DESCRIPTION
**Pull request by lionel-**
For consistency with rlang.

Includes #432.

### CODE REVIEW

**Comment by hadley** [comment]
Oh, this cause any new revdep failures?

**Comment by DavisVaughan** [comment]
I think this one might be clean. I don't use it in probably and the evaluator pkg doesn't seem to either

**Comment by lionel-** [comment]
Also we already cause failures because of signature consistency, since we have added `...` to generics, so it makes sense to bundle other breaking changes in this release.

**Comment by hadley** [comment]
I'm happy with breaking changes; just wanted to make sure it didn't introduce any new ones (I couldn't remember if you'd already done a round of notifications or not)

**Comment by lionel-** [comment]
oh it also needs to be `.fn` and `.x` to prevent matching with methods arguments

**Comment by hadley** [comment]
Oh good point!

**Pull request merged**
