### PR TITLE
Tweak vec_dim() documentation

### PR DESCRIPTION
**Pull request by krlmlr**
Is my understanding correct?

Follow-up to #467.

### CODE REVIEW

**Comment by lionel-** [comment]
I don't think we should document that `vec_dim()` returns length instead of size.

**Comment by krlmlr** [comment]
This represents the current implementation, I feel it's valuable as such. Do we have an issue that outlines the desired state?

**Comment by lionel-** [comment]
This is already documented as:

```
# FIXME: Should `vec_dim()` return the size instead of the length?
```

I think this represents better the status of the current implementation than making it look like the current semantics are well thought out.

I think the `FIXME` note is sufficient and I'd rather not have another open issue. `vec_dim()` is not used much in the package (but makes one test fail if we change it). We can figure it out later.

**Comment by lionel-** [comment]
Merging as we don't need to spend time on this.

**Pull request merged**
