### PR TITLE
Improve vec_as_location2 error message

### PR DESCRIPTION
**Pull request by 808sAndBR**
Resolves: #785 

To be consistent with some of the other error messages I saw in the package I adjusted the suggested message slightly from "a single valid subscript" to "a single valid subscript vector".

### CODE REVIEW

**Comment by DavisVaughan** [comment]
Thanks! I think we still prefer, "a single valid subscript". I think the addition of "vector" makes it slightly less clear that it really is a single _scalar_ value

**Comment by lionel-** [comment]
> To be consistent with some of the other error messages I saw in the package I adjusted the suggested message slightly from "a single valid subscript" to "a single valid subscript vector".

Hmm I think the original phrasing makes it clearer that a scalar is needed. From this perspective "vector" is giving the wrong signal. Can you remove it please?

**Comment by 808sAndBR** [comment]
Ohhhh I see now! Just pushed a fix to go back to the suggested phrasing.

**Comment by DavisVaughan** [comment]
Thank you!

**Pull request merged**
