### PR TITLE
Prefix error classes with vctrs_

### PR DESCRIPTION
**Pull request by krlmlr**
Not sure about the existing `"error_unimplemented"` and `"error_unsupported"` classes, do they need a prefix too?

The class names should be part of the documented API, too.

### CODE REVIEW

**Comment by krlmlr** [comment]
I like that approach. Should we start populating the _error_ package now?

**Comment by hadley** [comment]
No

**Comment by krlmlr** [comment]
Do we need to add/change anything here?

**Comment by krlmlr** [comment]
Merging so that we can move forward with #184. Let's discuss there if any changes are needed.

**Comment by hadley** [comment]
In the future, please don't merge with out approval from me.

**Pull request merged**
