### PR TITLE
Add missing `vec_cast()` methods for dates and datetimes

### LINKED ISSUE #715: Missing `vec_cast()` methods for date / datetime
- `vec_cast.character.Date()`
- `vec_cast.character.POSIXct()`
- `vec_cast.character.POSIXlt()`

Because their corresponding `double` methods exist:
- `vec_cast.Date.integer()`
- `vec_cast.POSIXct.integer()`
- `vec_cast.POSIXlt.integer()`

Should you be able to cast from Date/POSIXt -> double or integer as well to be symmetric here?

### PR DESCRIPTION
**Pull request by DavisVaughan**
Closes #715 

Should we also add the following methods for coercing to double/integer too?

- `vec_cast.integer.Date()`
- `vec_cast.double.Date()`
- `vec_cast.integer.POSIXct()`
- `vec_cast.double.POSIXct()`
- `vec_cast.integer.POSIXlt()`
- `vec_cast.double.POSIXlt()`

We don't have `vec_cast.integer.factor()` or `vec_cast.double.factor()` so I'd imagine no, but maybe we just don't have those because we really want a mental model of a factor as a restricted character vector?

### CODE REVIEW

**Comment by hadley** [comment]
I think casting to and from integers and doubles might be too relaxed?

**Comment by DavisVaughan** [comment]
I think that makes sense. That means that the double -> date/datetime methods that were already there should be removed, which I just did.

**Comment by lionel-** [comment]
This might have to wait for vctrs 0.3.0 since this restricts existing coercions.

Also, adding coercion methods for character might conflict with #606. The current idea is to remove most coercions from and to characters.

**Comment by lionel-** [comment]
Following last comments on Slack, it's probably less work to just keep `vec_cast()` as an arbitrary conversion generic, and introduce `vec_coerce()` for functions taking `.ptype` parameters, and for validating argument types in functions.

In that case, it's fine to include these character methods.

**Comment by DavisVaughan** [comment]
Closed in favor of #741 

See https://github.com/r-lib/vctrs/issues/715#issuecomment-573666136 for reasoning

**Pull request closed without merging**
