### PR TITLE
Export `vec_split_id()`

### LINKED ISSUE #514: export vec_duplicate_split()
For e.g. https://github.com/tidyverse/dplyr/pull/4504

`vec_duplicate_split()` gives exactly what is needed for a `vctrs` based implementation of `group_by()` , e.g. 

``` r
library(dplyr)

d <- tibble(x = c(1, 1, 1, 1, 2, 2), y = c(1, 2, 1, 2, 1, 2), z = 1:6)

vctrs:::vec_duplicate_split(select(d, x, y))
#> $key
#> [1] 1 2 5 6
#> 
#> $idx
#> $idx[[1]]
#> [1] 1 3
#> 
#> $idx[[2]]
#> [1] 2 4
#> 
#> $idx[[3]]
#> [1] 5
#> 
#> $idx[[4]]
#> [1] 6

group_by(d, x, y) %>% 
  group_data()
#> # A tibble: 4 x 3
#>       x     y .rows    
#> * <dbl> <dbl> <list>   
#> 1     1     1 <int [2]>
#> 2     1     2 <int [2]>
#> 3     2     1 <int [1]>
#> 4     2     2 <int [1]>
```

- `key` gives the indices I can use to `vec_slice()` the data to get the first columns
- `idx` is exactly the `.rows` column

https://github.com/tidyverse/dplyr/pull/4504 then goes a bit further to reveal empty groups when `.drop = FALSE` but that does not need to be `vctrs`' concern.

### PR DESCRIPTION
**Pull request by DavisVaughan**
Closes #514 
CC @romainfrancois 

- Renames `vec_duplicate_split()` as `vec_split_id()` and exports it
- `vec_split_id()` returns a data frame of the:
   - `key`: Unique values in `x`
   - `id`: A list of integers containing the positions of the keys in `x`
- `vec_split()` was updated to reflect the new api.

Questions:

- Should the `id` column be a `list_of<int()>`? We don't have a way to do this from the C side, so it would have to happen on the R side. As long as it doesn't affect performance much, it might make sense.
- Does using `out$id <- NULL` in `vec_split()` look okay? An alternative is creating a completely new data frame with `new_data_frame(list(key = out$key, val = vals))`, but I think it is slightly slower.

### CODE REVIEW

**Comment by DavisVaughan** [comment]
> Should the id column be a `list_of<int()>`?

Unfortunately this can be somewhat expensive to set at the R level with `new_list_of()` if `$id` is a long list of integers. This is due to the call to `attributes(x) <- attrib` in `vec_set_attributes()`. On R >=3.6 for atomic vectors this makes no copies (ALTREP), but it still has that ugly property of making 2 copies for objects like lists. The time would be cut in half if it only made 1 copy, and would be negligible if it made 0 copies.

``` r
library(vctrs)
library(nycflights13)

split <- vec_split_id(flights)
id <- split$id

# really long list of ints
length(id)
#> [1] 336776

bench::mark(new_list_of(id, ptype = integer()))
#> # A tibble: 1 x 6
#>   expression                            min median `itr/sec` mem_alloc
#>   <bch:expr>                         <bch:> <bch:>     <dbl> <bch:byt>
#> 1 new_list_of(id, ptype = integer()) 18.4ms 21.1ms      48.7    5.19MB
#> # … with 1 more variable: `gc/sec` <dbl>

profmem::profmem(new_list_of(id, ptype = integer()))
#> Rprofmem memory profiling of:
#> new_list_of(id, ptype = integer())
#> 
#> Memory allocations:
#> Number of 'new page' entries not displayed: 3
#>        what   bytes                                               calls
#> 4     alloc 2694256 new_list_of() -> new_vctr() -> vec_set_attributes()
#> 5     alloc 2694256 new_list_of() -> new_vctr() -> vec_set_attributes()
#> total       5388512

# for reference:
bench::mark(split <- vec_split_id(flights))
#> # A tibble: 1 x 6
#>   expression                        min median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>                     <bch:> <bch:>     <dbl> <bch:byt>    <dbl>
#> 1 split <- vec_split_id(flights)  107ms  107ms      9.32    52.3MB     18.6
```

From https://stat.ethz.ch/R-manual/R-devel/doc/html/NEWS.html

 "R-level assignments to change attributes will also use wrapper objects to avoid duplicating data for larger atomic vectors. R functions like structure() and unname() will therefore not duplicate data in these settings. Generic vectors as produced by list() are not yet covered by this optimization but may be in due course."

**Comment by hadley** [comment]
LGTM. Can't we just set the class and  the `ptype` attribute from C?

**Comment by lionel-** [comment]
> Should the id column be a list_of<int()>? 

I'm not sure there would be much point for such a low level function. Would it help detect some categories of bugs earlier? Also the returned data frame is not typed, so there's no internal invariant to enforce. Finally, maybe we should experiment with `list_of()` in leaf packages rather than a core one like vctrs?

**Comment by romainfrancois** [comment]
LGTM. updated https://github.com/tidyverse/dplyr/pull/4504 to use this.

**Comment by DavisVaughan** [comment]
Game plan:

- Implement ad hoc support for `list_of<int>` now.
- Add an issue for creating a `new_list_of()` constructor at the C level. 
   - Reference in the issue that we need to fix the ad hoc support
   - We would keep the `new_list_of()` R level constructor
   - This C constructor would be simplified by having no `...`, the caller can append extra attributes
   - It would use `SET_ATTRIB()` rather than `attributes<-`
   - Importantly it would only conditionally copy `x`. Since we aren't calling `attributes<-` this lets us fully avoid the double copy problem.

**Comment by DavisVaughan** [comment]
@lionel- if you could please review this commit when you get a moment, then I will merge https://github.com/r-lib/vctrs/pull/515/commits/5954be1959b715519fd54d224948543f73db13f9

**Comment by lionel-** [comment]
LGTM, this seems safe since the unit tests compare the ad hoc `list_of` to a one produced the normal way.

**Pull request merged**
