### PR TITLE
vec_ptype2(<factor>, <NA>)

### LINKED ISSUE #687: vec_ptype2(<factor>, <NA>)
``` r
library(vctrs)
vec_ptype2(NA, factor())
#> factor(0)
#> Levels:
vec_ptype2(factor(), NA)
#> Error: No common type for `x` <factor<>> and `y` <logical>.

sessioninfo::package_info("vctrs")
#>  package  * version    date       lib source                         
#>  digest     0.6.23     2019-11-23 [1] CRAN (R 3.6.0)                 
#>  ellipsis   0.2.0.9000 2019-10-05 [1] Github (r-lib/ellipsis@dc23a8c)
#>  glue       1.3.1.9000 2019-11-15 [1] Github (tidyverse/glue@c02d7d4)
#>  rlang      0.4.2      2019-11-25 [1] Github (r-lib/rlang@dbcb76f)   
#>  vctrs    * 0.2.0.9007 2019-11-25 [1] Github (r-lib/vctrs@f0171d2)   
#> 
#> [1] /Library/Frameworks/R.framework/Versions/3.6/Resources/library
```

<sup>Created on 2019-11-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

### PR DESCRIPTION
**Pull request by romainfrancois**
closes #687 

``` r
library(vctrs)
vec_ptype2(NA, factor())
#> factor(0)
#> Levels:
vec_ptype2(factor(), NA)
#> factor(0)
#> Levels:
```

Not sure that's the way to do this, or where I should add a test

### CODE REVIEW

**Comment by lionel-** [comment]
I think you just need to call `vec_default_ptype2()` from the default method, here: https://github.com/r-lib/vctrs/pull/688/files#diff-a2f11c2f565ab46c22a33a1872e92a01R69

See https://github.com/r-lib/vctrs/blob/master/R/type-bare.R#L141 for an example

**Comment by lionel-** [comment]
Can you also add tests please?

**Comment by romainfrancois** [comment]
The last added test is skipped because there is another issue: 

``` r
library(vctrs)

vec_ptype2(list_of(1, 2, 3), NA)
#> <list_of<double>[0]>
vec_ptype2(NA, list_of(1, 2, 3))
#> Error: No common type for `x` <logical> and `y` <list_of<double>>.
```

<sup>Created on 2019-11-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

**Comment by lionel-** [comment]
- Moved the tests to the specific `test-type-` files.

- The common type of list-of and `NA` is always an error. This way:

    ```
    vec_slice(x, 1) <- NA        # Fails
    vec_slice(x, 1) <- list(NA)  # Succeeds
    ```

**Comment by lionel-** [comment]
Thanks!

**Pull request merged**
