### PR TITLE
Allow integerish indexes in vec_as_index()

### LINKED ISSUE #577: Allow integerish indexes in vec_as_index()
Does this need to be an error?

``` r
vctrs::vec_as_index(1:3, 3)
#> `n` must be a vector with type <integer>.
#> Instead, it has type <double>.
```

<sup>Created on 2019-09-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### PR DESCRIPTION
**Pull request by krlmlr**
With implicit tests.

Closes #577.

### CODE REVIEW

**Comment by lionel-** [comment]
I don't like the unnecessarily large diff in unit tests here. Can you just add a single test checking that double indices are allowed please, and maybe check that lossy casts (e.g. `n = 1.5`) are an error.

**Comment by krlmlr** [comment]
I agree. 6212821 contains the removal of the `L`s as a separate commit, feel free to cherry-pick.

**Comment by lionel-** [comment]
I will. But also feel free to rebase and force-push.

**Comment by krlmlr** [comment]
I don't understand. Can we please merge this as is and discuss `L` afterwards?

**Comment by lionel-** [comment]
No need to discuss `L` afterwards, I just meant to leave it out of the PR which is now the case, thanks!

**Pull request merged**
