### PR TITLE
Use `vctrs_error_scalar_type` class in `expect_error()`

### PR DESCRIPTION
**Pull request by DavisVaughan**
This was throwing warnings for me with the latest version of testthat

### CODE REVIEW

**Comment by lionel-** [comment]
Can you leave the testing of message contents please?

**Comment by hadley** [comment]
Is that important for this case?

**Comment by lionel-** [comment]
I guess if the message doesn't vary as a function of inputs it doesn't matter.

**Comment by lionel-** [comment]
Thanks!

**Pull request merged**
