### PR TITLE
Add life cycle badges for generics and functions used in pillar

### PR DESCRIPTION
**Pull request by krlmlr**
Closes https://github.com/r-lib/pillar/issues/164.

### CODE REVIEW

**Comment by krlmlr** [comment]
Below is an overview of the functions used by dev {hms} and {blob}. This is only part of the story, a coverage analysis with `x <- covr::package_coverage(type = "none", code = 'devtools::test("../blob")')` reveals implicit usage of methods.

@lionel-: Can we declare these functions as "maturing"? How do we use the life cycle badges to describe stability of the behavior of methods?

``` r
library(tidyverse)
library(glue)

rlang::set_names(c("hms", "blob")) %>%
  map(itdepends::dep_usage_pkg) %>%
  enframe("our_pkg") %>%
  unnest() %>%
  filter(pkg == "vctrs") %>%
  count(fun, our_pkg) %>%
  group_by(fun) %>%
  summarize(our_pkg = glue_collapse(glue("{our_pkg} ({n})"), ", ")) %>%
  ungroup()
#> # A tibble: 14 x 2
#>    fun                    our_pkg           
#>    <chr>                  <glue>            
#>  1 new_datetime           hms (3)           
#>  2 new_duration           hms (1)           
#>  3 new_list_of            blob (1)          
#>  4 s3_register            blob (2), hms (1) 
#>  5 stop_incompatible_cast blob (1), hms (1) 
#>  6 stop_incompatible_type blob (1), hms (1) 
#>  7 vec_assert             hms (1)           
#>  8 vec_c                  hms (1)           
#>  9 vec_cast               blob (1), hms (10)
#> 10 vec_data               blob (1), hms (5) 
#> 11 vec_default_cast       blob (1), hms (1) 
#> 12 vec_is                 blob (1)          
#> 13 vec_restore            hms (3)           
#> 14 vec_slice              hms (1)
```

<sup>Created on 2019-05-30 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by lionel-** [comment]
The whole package will probably be promoted to maturing at the next release.

**Comment by krlmlr** [comment]
Thanks. I'll leave this open until we decide.

I'd like to submit hms and blob to CRAN. Off the top of your head, are you anticipating substantial changes to the functions these packages are calling?

**Comment by lionel-** [comment]
`vec_data()` should probably take the proxy before stripping attributes and `vec_cast()` will probably gain a `...` parameter.

The UI of `vec_assert()` and `vec_is()` is still under discussion.

**Comment by krlmlr** [comment]
I can't make blob work with CRAN vctrs, and hms uses `vec_assert()` (#345).

**Comment by lionel-** [comment]
We plan to release vctrs within the month, I suggest waiting until then. Closing this since the next release should be promoted to maturing, as tidyr will quickly depend on it.

**Pull request closed without merging**
